<?php
$games = [
    ['type'=>'Slot','code'=>'sldd','name'=>'Diamond Dream'],
    ['type'=>'Slot','code'=>'slan','name'=>'Arabian Nights'],
    ['type'=>'Slot','code'=>'slbc','name'=>'Big City Night'],
    ['type'=>'Slot','code'=>'slbv','name'=>'Bon Voyage'],
    ['type'=>'Slot','code'=>'slca','name'=>'Cabaret'],
    ['type'=>'Slot','code'=>'slmm','name'=>'Magic Mushroom'],
    ['type'=>'Slot','code'=>'slps','name'=>'Pirates'],
    ['type'=>'Slot','code'=>'slrm','name'=>'Russian Myth'],
    ['type'=>'Slot','code'=>'slcg','name'=>'Chicago'],
    ['type'=>'Slot','code'=>'slrt','name'=>'Reef Treasure'],
    ['type'=>'Slot','code'=>'slsd','name'=>'Sweet Dream'],
    ['type'=>'Slot','code'=>'slde','name'=>'Diamond Dream Deluxe'],
    ['type'=>'Slot','code'=>'sldl','name'=>'Demobee'],
    ['type'=>'Slot','code'=>'sldw','name'=>'Dwarves'],
    ['type'=>'Slot','code'=>'slce','name'=>'Cruise'],
    ['type'=>'Slot','code'=>'slcr','name'=>'Circus'],
    ['type'=>'Slot','code'=>'slds','name'=>'Dark Side'],
    ['type'=>'Slot','code'=>'slgf','name'=>'Golden Fiesta'],
    ['type'=>'Slot','code'=>'sltr','name'=>'Tropicana'],
    ['type'=>'Slot','code'=>'slhh','name'=>'Happy Holiday'],
    ['type'=>'Slot','code'=>'slhu','name'=>'Hunter'],
    ['type'=>'Slot','code'=>'slsa','name'=>'Samurai'],
    ['type'=>'Slot','code'=>'sluf','name'=>'Little Green man'],
    ['type'=>'Slot','code'=>'slfz','name'=>'Fun Zoo'],
    ['type'=>'Slot','code'=>'slsl','name'=>'Sheriffs Life'],
    ['type'=>'Slot','code'=>'sleg','name'=>'Gold of Egypt'],
    ['type'=>'Slot','code'=>'slru','name'=>'Russian Tales'],
    ['type'=>'Slot','code'=>'slve','name'=>'Viking Expansion'],
    ['type'=>'Slot','code'=>'slwf','name'=>'Wheels of Fire'],
    ['type'=>'Slot','code'=>'slgt','name'=>'Gelateria'],
    ['type'=>'Slot','code'=>'slls','name'=>'Lucky Shamrock'],
    ['type'=>'Slot','code'=>'slvi','name'=>'Vino'],
    ['type'=>'Slot','code'=>'slfa','name'=>'Happy Farm'],
    ['type'=>'Slot','code'=>'slmu','name'=>'Mummy'],
    ['type'=>'Slot','code'=>'slmr','name'=>'Mister Mania'],
    ['type'=>'Slot','code'=>'slgth5','name'=>'Gelateria HTML5 version'],
    ['type'=>'Slot','code'=>'sllsh5','name'=>'Lucky Shamrock HTML5 version'],
    ['type'=>'Slot','code'=>'slvih5','name'=>'Vino HTML5 version'],
    ['type'=>'Slot','code'=>'slfah5','name'=>'Happy Farm HTML5 version'],
    ['type'=>'Slot','code'=>'slmuh5','name'=>'Mummy HTML5 version'],
    ['type'=>'Slot','code'=>'slmrh5','name'=>'Mister Mania HTML5 version'],
    ['type'=>'Slot','code'=>'slre','name'=>'Refresher'],
    ['type'=>'Slot','code'=>'slreh5','name'=>'Refresher HTML5 version'],
    ['type'=>'Slot','code'=>'slsf','name'=>'Smile of Fortune'],
    ['type'=>'Slot','code'=>'slsfh5','name'=>'Smile of Fortune HTML5 version'],
    ['type'=>'Slot','code'=>'slbe','name'=>'Game of Bear'],
    ['type'=>'Slot','code'=>'slbeh5','name'=>'Game of Bear HTML5 version'],
    ['type'=>'Poker','code'=>'pkgo','name'=>'Poker Golden Oasis'],
    ['type'=>'Poker','code'=>'pkru','name'=>'Russian Poker'],
    ['type'=>'Poker','code'=>'pkth','name'=>'Texas Hold\'em'],
    ['type'=>'Poker','code'=>'pktp','name'=>'Texas Poker'],
    ['type'=>'Videopoker','code'=>'vpjb','name'=>'Videopoker Jacks or Better'],
    ['type'=>'Videopoker','code'=>'vpjp','name'=>'Videopoker Joker Poker'],
    ['type'=>'Videopoker','code'=>'vptb','name'=>'Videopoker Tens or Better'],
    ['type'=>'Videopoker','code'=>'vpdw','name'=>'Videopoker Dewces Wild'],
    ['type'=>'Videopoker','code'=>'vpjbh5','name'=>'Videopoker Jacks or Better HTML5 version'],
    ['type'=>'Videopoker','code'=>'vpjph5','name'=>'Videopoker Joker Poker HTML5 version'],
    ['type'=>'Videopoker','code'=>'vptbh5','name'=>'Videopoker Tens or Better HTML5 version'],
    ['type'=>'Videopoker','code'=>'vpdwh5','name'=>'Videopoker Dewces Wild HTML5 version'],
    ['type'=>'Blackjack','code'=>'bjbj','name'=>'Blackjack'],
    ['type'=>'Roulette','code'=>'roam','name'=>'American 4-table Roulette'],
    ['type'=>'Roulette','code'=>'roeu','name'=>'European Roulette'],
    ['type'=>'Roulette','code'=>'roeuvip','name'=>'European Roulette VIP'],
    ['type'=>'Roulette','code'=>'roeua','name'=>'European Roulette A'],
    ['type'=>'Roulette','code'=>'roeuavip','name'=>'European Roulette A VIP'],
    ['type'=>'Roulette','code'=>'rowz','name'=>'Roulette without Zero'],
    ['type'=>'Roulette','code'=>'rowza','name'=>'Roulette without Zero A'],
    ['type'=>'Roulette','code'=>'rowzavip','name'=>'Roulette without Zero A VIP'],
    ['type'=>'Roulette','code'=>'roeuh5','name'=>'European Roulette HTML5 version'],
];
